branches:
  only:
  - /^[0-9]+\.[0-9]+.*/
  - master

if: tag IS present OR type = api

language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic

env:
  global:
  - CIBW_SKIP="?p27-*"
  - CIBW_BUILD_VERBOSITY=3
  - BUILD_OUTPUT_PATH="wheelhouse"
  - TWINE_USERNAME="cher-nov"
  - secure:
      "aBRrofA6DIuKfuhrWzWrQCpe6dLH25yKPO9ID1+jwZtWp9Z+6bYMknSCOyHE5YkUpJmspf\
      R+GQsDya4cENC8MUweyEXWVQ09POcjOvUycJDpVNAFOhn0G+ygFlvIzpEdbBB6a0zQad0Mr\
      VcLZYyMRLEuDXjCyplZH2Rca7UhHR1Fo78jxT5RHlVN2Hqwb6qmKUiowA2npvp4S2pM1FPC\
      +sKR14ElKWN//digHFQHmtZIGoZVt8RglnmHCnykJ9Pt2aqH07zqg793ubuGEnFOJNbhrhS\
      uS09A1W2EMl6wLw1MkiwT5rql1SrvkbYAU8DL9jGwkZjjvGrBJpVwXBEMEAoUSNXFeYn2gx\
      wV7drzuFFRLk2+ogu0rfVkUi3DFG5sipmtuzw+fSZPCCrkvxYHlPpP5j6Oi4w3rBetBdG93\
      1vG6zhzuxC6Y5nVlZuYVeRoDHUo7pS3JdvBzSBvCvptlaWQMMUo9wnk998I+2O6mqrkw020\
      X+TDaSmv8+8cpmP3d0XCxuwEnGFlUXK1/PkAnQApaRwXRYuRczRn7gooG7oVQ/6nG+hFOvS\
      bI9SUjgDI9fwlnItoyI90LhLJXXFAiSrT+4CU4ydehZRkQVA1I5nlxbJlBeC24AkOVQcxX8\
      Yb7EdXHBH8bcQDXpcf1ytKCnXnCoVBdYJtxQcaD2YutoM="

install: |
  pip install twine cibuildwheel

before_script: |
  if [[ -n "$CI_TEST_LAUNCH" ]]; then
    echo "THIS IS A TEST LAUNCH!"
    export PYPI_SETUP_VERSION_SUFFIX="dev999$TRAVIS_BUILD_ID"
    export TWINE_REPOSITORY_URL="https://test.pypi.org/legacy/"
    export CIBW_ENVIRONMENT_LINUX="\
      PYPI_SETUP_VERSION_SUFFIX=\"$PYPI_SETUP_VERSION_SUFFIX\""
  fi

script: |
  cibuildwheel --output-dir $BUILD_OUTPUT_PATH

after_success: |
  twine upload --skip-existing "$BUILD_OUTPUT_PATH/*.whl"
