[package]
name = "cryptg"
version = "0.1.0"
authors = ["Lonami Exo <totufals@hotmail.com>"]
edition = "2018"

[dependencies]
grammers-crypto = "0.7.0"
pyo3 = { version = "0.22.4", features = ["extension-module"] }

[lib]
name = "cryptg"
crate-type = ["cdylib"]
